spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  devtools:
    restart:
      log-condition-evaluation-delta: true