spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
